export interface CountryCode {
  "bd": string
  "be": string
  "bf": string
  "bg": string
  "ba": string
  "bb": string
  "wf": string
  "bl": string
  "bm": string
  "bn": string
  "bo": string
  "bh": string
  "bi": string
  "bj": string
  "bt": string
  "jm": string
  "bv": string
  "bw": string
  "ws": string
  "bq": string
  "br": string
  "bs": string
  "je": string
  "by": string
  "bz": string
  "ru": string
  "rw": string
  "rs": string
  "tl": string
  "re": string
  "tm": string
  "tj": string
  "ro": string
  "tk": string
  "gw": string
  "gu": string
  "gt": string
  "gs": string,
  "gr": string
  "gq": string
  "gp": string
  "jp": string
  "gy": string
  "gg": string
  "gf": string
  "ge": string
  "gd": string
  "gb": string
  "ga": string
  "sv": string
  "gn": string
  "gm": string
  "gl": string
  "gi": string
  "gh": string
  "om": string
  "tn": string
  "jo": string
  "hr": string
  "ht": string
  "hu": string
  "hk": string
  "hn": string
  "hm": string
  "ve": string
  "pr": string
  "ps": string
  "pw": string
  "pt": string
  "sj": string
  "py": string
  "iq": string
  "pa": string
  "pf": string
  "pg": string
  "pe": string
  "pk": string
  "ph": string
  "pn": string
  "pl": string
  "pm": string
  "zm": string
  "eh": string
  "ee": string
  "eg": string
  "za": string
  "ec": string
  "it": string
  "vn": string
  "sb": string
  "et": string
  "so": string
  "zw": string
  "sa": string
  "es": string
  "er": string
  "me": string
  "md": string
  "mg": string
  "mf": string
  "ma": string
  "mc": string
  "uz": string
  "mm": string
  "ml": string
  "mo": string
  "mn": string
  "mh": string
  "mk": string
  "mu": string
  "mt": string
  "mw": string
  "mv": string
  "mq": string
  "mp": string
  "ms": string
  "mr": string
  "im": string
  "ug": string
  "tz": string
  "my": string
  "mx": string
  "il": string
  "fr": string
  "io": string
  "sh": string
  "fi": string
  "fj": string
  "fk": string
  "fm": string
  "fo": string
  "ni": string
  "nl": string
  "no": string
  "na": string
  "vu": string
  "nc": string
  "ne": string
  "nf": string
  "ng": string
  "nz": string
  "np": string
  "nr": string
  "nu": string
  "ck": string
  "xk": string
  "ci": string
  "ch": string
  "co": string
  "cn": string
  "cm": string
  "cl": string
  "cc": string
  "ca": string
  "cg": string
  "cf": string
  "cd": string
  "cz": string
  "cy": string
  "cx": string
  "cr": string
  "cw": string
  "cv": string
  "cu": string
  "sz": string
  "sy": string
  "sx": string
  "kg": string
  "ke": string
  "ss": string
  "sr": string
  "ki": string
  "kh": string
  "kn": string
  "km": string
  "st": string
  "sk": string
  "kr": string
  "si": string
  "kp": string
  "kw": string
  "sn": string
  "sm": string
  "sl": string
  "sc": string
  "kz": string
  "ky": string
  "sg": string
  "se": string
  "sd": string
  "do": string
  "dm": string
  "dj": string
  "dk": string
  "vg": string
  "de": string
  "ye": string
  "dz": string
  "us": string
  "uy": string
  "yt": string
  "um": string
  "lb": string
  "lc": string
  "la": string
  "tv": string
  "tw": string
  "tt": string
  "tr": string
  "lk": string
  "li": string
  "lv": string
  "to": string
  "lt": string
  "lu": string
  "lr": string
  "ls": string
  "th": string
  "tf": string
  "tg": string
  "td": string
  "tc": string
  "ly": string
  "va": string
  "vc": string
  "ae": string
  "ad": string
  "ag": string
  "af": string
  "ai": string
  "vi": string
  "is": string
  "ir": string
  "am": string
  "al": string
  "ao": string
  "aq": string
  "as": string
  "ar": string
  "au": string
  "at": string
  "aw": string
  "in": string
  "ax": string
  "az": string
  "ie": string
  "id": string
  "ua": string
  "qa": string
  "mz": string
}